# Generated by Django 5.1.3 on 2024-11-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponguser',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
